name: "💡 Create Story"
description: Create a new ticket for a story
title: ""
labels: [
  "Story"
]
body:
  - type: textarea
    id: user_story
    attributes:
      label: "User Story"
      description: Provide the user story needed to fulfill this feature
      placeholder: As a [type of user], I want to [perform an action] so that [I can achieve a goal].
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      description: Indicate the acceptance criteria of this story
      value: |
        Acceptance Criteria:
        - 
    validations:
      required: true
  - type: textarea
    id: definition_of_done
    attributes:
      label: "Definition of Done"
      description: Indicate the overall definition of done for this story
      value: |
        - Code updated
        - Test suite passing
        - QA/Peer review completed
        - Documentation updated
    validations:
      required: true
